### ISSUE TITLE
Consider updating the link of cpp in tuio.org to this repo

### ISSUE THREAD

**Issue by nunoh** [mkalten/TUIO11_CPP#1]
When compiling the contents of the `TUIO11_CPP.zip` file downloaded from TUIO.org the Makefile was trying to compile files that weren't included in the distribution, namely `DevSender.cpp` and `DevReceiver.cpp`, what ends up resulting in a make compilation error. The same problem doesn't seem to exist with this repo in GH. I'm assuming that you are affiliated somehow to the website and hence leaving the issue here. 

Cheers and thanks for TUIO! :+1:

**Comment by mkalten** [comment]
Hi @nunoh, I will eventually replace the current release, but since the fix can be done easily and most people may anyway just use the latest code from Github this is not a major problem I guess. In any case I will publish a refreshed 1.1.6 together with the next version of reacTIVision.

**Comment by GuillaumeLazar** [comment]
@nunoh +1
