### ISSUE TITLE
Ractiv's TouchPlus 3D Stereo Camera software using TUIO cursor

### ISSUE THREAD

**Issue by touchhope** [mkalten/TUIO11_CPP#2]
Hi Martin,

Sorry to pollute your github with our desperate search for technical solution. Here's our story around the TUIO cursor :

I'm Touchhope, a Ractiv's TouchPlus 3D Stereo Camera french buyer at http://gharbi.me/ractiv/ , our community of backers and buyers who have been rolled in flour.

Indeed, first units were sold from august 5th 2014 by Ractiv and I was in the first people to buy on their lovely website http://www.ractiv.com/ but from october 5th 2014, no more communication with customers at http://www.ractiv.com/blog/setting-up-touch/.

Only few words sometimes from one of the founders of this Kickstarter project (see : https://www.kickstarter.com/projects/haptix/haptix-multitouch-reinvented/comments ), Lai Schwe from Shanghai, on their github site at https://github.com/Ractiv and a confidential first buggy 0.55b compiled release briefly upload to pan.baidu.com , see https://www.youtube.com/watch?v=ulFTmjiwmAA

Then we had few weeks during august 2015 debugging with Lai Schwe (see : https://github.com/Ractiv/touch_plus_source_code/issues/8).

Then nothing from the end of 2015 october when Lai Schwe announced us on a regular update on gitbub that Ractiv's members were starting to leave the team, including Corey Manders from IEEE and Institute Of Infocomm Research, Singapore.

Corey did communicate with me for a while but he's now too busy at this time. He made the SDK at https://github.com/Ractiv/TouchPlus .

Umar Nizamani from Nerdiacs has hacked (https://medium.com/@Rapchik/hacking-the-ractiv-touch-79a02aa003e#.bv5w7xcaz) last year some codes on Etron's eSP870 who powered the unit, see at https://github.com/umarniz/TouchPlusLib/ and I've communicate with him recently and he said "I did go through the code for a couple of hours a few weeks back and in its current state it has been left in a debug state where the dev was midway through adding some functionality and has lots of testing code splattered across the code. Secondly the code has very few comments which makes it very hard to understand functionality throughout.I think for it to be fully functional and usable it would require a lot of time to work on it."

I also get in contact with Dr. Andrea Tagliasacchi, Assistant Professor, Graphics Laboratory @ University of Victoria, BC Canada, Department of Computer Science, see at http://gfx.uvic.ca/people/ataiya/ but he's working on Intel Realsense SR300 and was asking me for unknown parameters "comparison in terms of variance of z-noise, precision of silhouette images, range of operation and frame rate" to see if he was really interested for testing and adapting with his own algorithm.

Maz (friend of autralian backer Lachlan Pollock from Adelaide at http://gharbi.me/ractiv/) and his team on OpenCV from California will also maybe have a look at the hardware as well as test software.

As I saw your work on TUIO on internet which is used in this project, I was thinking of you to maybe give us some help if our community could provide you with a unit (some members made donation proposals, some bought more than one unit).

The software in its actual state on github at https://github.com/Ractiv/touch_plus_source_code don't send anything to udp channel to win_cursor_plus process, see at https://github.com/Ractiv/touch_plus_source_code/issues/37.

However, I'm currently testing several old commits in VS2015 community, and for now especially commit 9731adc "Finally figured out how SFML UDP works" on Aug 25, 2015 : https://github.com/Ractiv/touch_plus_source_code/tree/9731adcfdc1194c8856be0e3c8137149c95c8406
after downloaded clicking on "Clone or download", I've uncommented all I've found in files and set to true "IsHitTestVisible="True" ShowInTaskbar="True"" in MainWindow.xaml file in C:\touch_plus_source_code\track_plus_visual_studio\win_cursor_plus folder, I've finally got track_plus.exe and win_cursor_plus.exe processes launched as seen in taskmgr. #define SHOW_CONSOLE" is commented in file track_plus_core/daemon_plus/globals.h to avoid console mode and so daemon_plus.exe is unloaded and menu_plus.exe is reduced while running. I obtain a windowed MainWindow in taskbar below, but when right clicking on "win_cursor_plus" I only get an UAC message to relaunch process as administrator. However, I see percent of ressources used by the running process while moving my fingers, so I think udp messages are exchanged.

Unfortunately, I'm not gifted enough to solve it on my own. No man is an island as backer Robert Sweetman said, but I'm actually feeling like Robison Crusoe on his island !

Could it be an evident reason for TUIO cursor (version 1.4) not being properly functionning from csharp "win_cursor_plus" process, as seen on https://www.youtube.com/watch?v=ulFTmjiwmAA ?

Maybe some uncompatibility with windows 10 or simply wrong parameters to get launched or firewall preventing any execution ?

Well, I supposed, as everyone, you don't have too much time to spend on this "sinking" project, as Dr Tagliasacchi said, but I thought it was worth to ask you if we eventually could use a little bit of your knowledge.

Thanks in advance for your response, even if negative, I would obviously understand as I said to Dr Tagliasacchi.

Cheers,

Christian or Touchhope at http://gharbi.me/ractiv/

**Comment by mkalten** [comment]
hi @touchhope, honestly I never heard of this device before ... looks interesting though.
as far as I understand, the manufacturer left you with non-functional drivers and sdk?
from what I saw quickly reviewing their code, they are using the CSHARP TUIO client in their software,
which may be a hint that their driver actually sends touch data encoded as /tuio/2Dcur cursors.

you could try to use one of the available TUIO client demos for any platform or language and see if you can receive anything on their UDP port (which seems to be different from the standard TUIO UDP port 3333)

you could also try to update the TUIO CSHARP code, which would also be the right place for this discussion, since this here is the C++ version ... https://github.com/mkalten/TUIO11_NET

if you want to provide me with such a device, I can have a closer look of course

edit: it also seems that they modified/extended the TUIO protocol, which probably results in making it incompatible with standard TUIO software. what's exactly the function of the  win_cursor_plus component?
